name: Bookdown Preview

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: rstudio/r-base:3.6-bionic
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install System Dependencies
        run: sudo apt-get update && apt-get install -y --no-install-recommends
      - name: Install Bookdown
        run: |-
          Rscript -e "install.packages('bookdown', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Build book
        run: |-
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: chris-diaz@northwestern.edu # must be a verified email
          GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
          BUILD_DIR: _book/                     # "_site/" by default
